### ISSUE TITLE
CONFIG_USB_XHCI_HCD=m - Enable USB3

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#11]
Hello Robert,

for boards with USB3 (e.g. ODROID) it would be reasonable to enable CONFIG_USB_XHCI_HCD.

In Debian this is enabled as module by default.

Best regards

Heinrich Schuchardt

**Comment by RobertCNelson** [comment]
Thanks for the hint Heinrich.. Actually just got my odroid-xu in the mail over the weekend, so this will need this too..

BTW, would this make more sense for v3.12-rc1, or does the device work fine in v3.11... (i'm still just a little behind after a weekend/vacation..)  Hoping to merge my current v3.12-rc1 tree to armv7-multiplatform this afternoon...

Regards,

**Comment by RobertCNelson** [comment]
Fixed: https://github.com/RobertCNelson/armv7-multiplatform/commit/f289787048a287296af33891ea2fb4a72930dafc
