### ISSUE TITLE
CONFIG_DEBUG_GPIO

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#12]
Hello Robert,

on my Wandboard Quad dmesg for kernel 3.12 shows messages like
[ 2.001931] of_get_named_gpio_flags: can't parse gpios property of node '/regulators/2p5v[0]' 

Fabio Estevam wrote to me:
In order to silence these debug messages: just unselect 
CONFIG_DEBUG_GPIO from the defconfig and they will not show up anymore.

Best regards

Heinrich Schuchardt

**Comment by RobertCNelson** [comment]
Yeah we can disable it..

btw, are you getting something similar to this:
http://pastebin.com/p3x8W16e

Just noticed it today when i moved my farm to v3.12-rc4, then had to move it back as it eventually hardlocked..

WandBoard setup as: mmc boot, sata rootfs...

(side note: i should mention i really trash these sata rootfs with development kernel testing, so the OS could be easily hosed, as it's about 2 months old now.)

**Comment by xypron** [comment]
Hello Robert,

I am still on rc3

Regards

Heinrich

**Comment by xypron** [comment]
Fabio Estevam created this patch:
http://www.spinics.net/lists/arm-kernel/msg278362.html

**Comment by RobertCNelson** [comment]
fixed on: https://github.com/RobertCNelson/armv7-multiplatform/commit/a23be5ef411863b5166dc2e8bdbc61106e03602a
