### ISSUE TITLE
Freescale imx on 3.10 kernel no network device detected

### ISSUE THREAD

**Issue by geosone** [RobertCNelson/armv7-multiplatform#14]
for some to me unknown reasons the nic won't get detected correctly
https://gist.github.com/geosone/7367056

**Comment by RobertCNelson** [comment]
Weird it's working for me:

root@arm:/home/debian# uname -a
Linux arm 3.10.18-armv7-x4.4 #1 SMP Thu Nov 7 12:04:26 CST 2013 armv7l GNU/Linux

root@arm:/home/debian# dhclient eth0
[   73.236703] fec 63fec000.ethernet eth0: Freescale FEC PHY driver [SMSC LAN8710/LAN8720](mii_bus:phy_addr=63fec000.etherne:00, irq=-1)
[   73.249109] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   75.236702] libphy: 63fec000.etherne:00 - Link is Up - 100/Full
[   75.242737] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

root@arm:/home/debian# /sbin/ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:04:9f:01:81:63  
          inet addr:192.168.0.169  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::204:9fff:fe01:8163/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1078 (1.0 KiB)  TX bytes:0 (0.0 B)

But i'm not booting from sata, just he microSD so maybe???

**Comment by geosone** [comment]
yes i am still looking for the reason if i find something i will let you knoow.
for thest i am switching back to the original u-boot with no fdt for me it looks like uboot is not initializing the nic correctly if sata

**Comment by geosone** [comment]
i think my nic is burned bad 
 time to buy a wandboard

**Comment by geosone** [comment]
boot without sata only mmc same no network so now its clear the nic is broken
