### ISSUE TITLE
[PATCH] Use standardized name for config file.

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#15]
<pre>
Most Linux distributions (e.g. Debian, Fedora) use
/boot/config-$(uname -r)
for the Kernel configuration file.

Hence the deploy directory should also contain a file of this name.
The user can copy this file to directory /boot without renaming.

Signed-off-by: Heinrich Schuchardt &lt;xypron.glpk@gmx.de&gt;

---
 build_kernel.sh | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/build_kernel.sh b/build_kernel.sh
index 80e5a87..6f76eea 100755
--- a/build_kernel.sh
+++ b/build_kernel.sh
@@ -89,7 +89,7 @@ make_kernel () {
 
        if [ -f "${DIR}/deploy/${KERNEL_UTS}.${image}" ] ; then
                rm -rf "${DIR}/deploy/${KERNEL_UTS}.${image}" || true
-               rm -rf "${DIR}/deploy/${KERNEL_UTS}.config" || true
+               rm -rf "${DIR}/deploy/config-${KERNEL_UTS}" || true
        fi
 
        if [ -f ./arch/arm/boot/${image} ] ; then
@@ -99,10 +99,10 @@ make_kernel () {
                        xz -z "${DIR}/deploy/beagleboard.org/${KERNEL_UTS}/${KERNEL_UTS}.${image}"
                        mkimage -A arm -O linux -T kernel -C none -a 0x80008000 -e 0x80008000 -n ${KERNEL_UTS} -d arch/arm/boot/zImage "${DIR}/deploy/beagleboard.org/${KERNEL_UTS}/${KERNEL_UTS}.uImage"
                        xz -z "${DIR}/deploy/beagleboard.org/${KERNEL_UTS}/${KERNEL_UTS}.uImage"
-                       cp -uv .config "${DIR}/deploy/beagleboard.org/${KERNEL_UTS}/${KERNEL_UTS}.config"
+                       cp -uv .config "${DIR}/deploy/beagleboard.org/${KERNEL_UTS}/config-${KERNEL_UTS}"
                fi
                cp -v arch/arm/boot/${image} "${DIR}/deploy/${KERNEL_UTS}.${image}"
-               cp -v .config "${DIR}/deploy/${KERNEL_UTS}.config"
+               cp -v .config "${DIR}/deploy/config-${KERNEL_UTS}"
        fi
 
        cd ${DIR}/
-- 
1.8.4.3
</pre>

**Comment by RobertCNelson** [comment]
Thanks Heinrich, that's a nice idea.

I just pushed it as:
https://github.com/RobertCNelson/stable-kernel/commit/ca1098b7e33bf384c0036ca52112f1b0fa4c0160
and added the config-xyz to /boot/ copy in the tools/install_kernel.sh script...

**Comment by xypron** [comment]
Will you push it to armv7-multiplatform too?
