### ISSUE TITLE
KVM

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#16]
Hello Robert,

I would like to use KVM on my wandboard.

Could this be added generally or would some board supported by  armv7-multiplatform be incompatible to LPAE?

The config flags in question are:
<Y> LPAE (-> System Type)
<Y> KVM (-> Virtualization (VIRTUALIZATION [=y]))
<Y> PCI (-> Bus support)
<M> DRM_QXL (-> Device Drivers -> Graphics support)

Debian uses these additional flags for LPAE:
CONFIG_ARM_DMA_USE_IOMMU=y
CONFIG_ARM_DMA_IOMMU_ALIGNMENT=8
CONFIG_ARM_SMMU=y

Best regards

Heinrich Schuchardt

**Comment by RobertCNelson** [comment]
Hi Heinrich,

I don't believe the Cortex A9 supports kvm, unless v3.13-rcX now also includes an emulation layer for the A9's.. I'm only 100% sure the A15's has them.

Yes, i'm also planning a lpae branch for A15's, which will also have kvm enabled by default.

Regards,
