### ISSUE TITLE
zram

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#17]
zram allows to use part of the RAM as compressed swap.

With this commit it has been moved from staging to drivers main:
https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/commit/?id=ab41c488c652be9ed08e5b1660727147df27e8cd

Kernel module zram is available in Ubuntu by default.

Hence I suggest to add the module to the default configuration of armv7-multiplatform.

Usage is described here:
http://askubuntu.com/questions/302447/how-to-install-zram-on-ubuntu-13-04
https://github.com/mystilleef/FedoraZram
http://lists.debian.org/debian-devel/2012/01/msg00210.html

**Comment by RobertCNelson** [comment]
Yeah, i was reading that too.. What config are we missing?  btw, don't we need a userspace side to make this work too, do you know what packages are needed?

**Comment by xypron** [comment]
Debian package mount contains:
/sbin/swapon,and /sbin/swapoff

Debian package util-linux contains:
/sbin/mkswap

**Comment by RobertCNelson** [comment]
Oh i was thinking there was a zram-config utility or something..  Just enabled the two missing configs:
https://github.com/RobertCNelson/armv7-multiplatform/commit/aa1874765b8f0c3554072d6eb4f602fb6e2510a2

CONFIG_ZSMALLOC=y
CONFIG_ZRAM=m

**Comment by RobertCNelson** [comment]
BTW: i've started config checker, for better enablement of features and more consistency..
https://github.com/RobertCNelson/stable-kernel/blob/master/tools/config-checker.sh
