### ISSUE TITLE
Vivante GPU acceleration

### ISSUE THREAD

**Issue by madduci** [RobertCNelson/armv7-multiplatform#19]
I've added the GPU driver module for Vivante GC for kernel 3.13. It compiles successfully.

The patch which enables the driver is defined here:

https://dl.dropboxusercontent.com/u/4276487/0002-ARM-i.MX6-Wandboard-add-Vivante-GPU-Driver.patch

**Comment by RobertCNelson** [comment]
That's crazy!  That's the first 'drm' driver i've ever seen for arm... where's the userspace stuff located?

Just to stay in sync with upstream, i'll watch/cherry pick from here:
http://git.freescale.com/git/cgit.cgi/imx/linux-2.6-imx.git/log/drivers/gpu/drm/vivante?h=imx_3.10.17_1.0.0_beta&id=2d570481f146218b5148930b573401070526cc1a

**Comment by madduci** [comment]
Sure. I took the source code from the alpha 3.10.9 kernel of Freescale and
make it compiling for 3.13 as something was missing.

If you check the source code, it's the same I've created with the patch
I've sent you.
Vivante DRM driver is 'poor' compared to exynos or others, because the
Vivante GAL, EGL libraries are responsible of 3D acceleration. This driver
is just the base step to make those armhf libraries working, as they
require the kernel module.

Kind regards,
Michele
Am 08.01.2014 16:28 schrieb "Robert Nelson" notifications@github.com:

**Comment by RobertCNelson** [comment]
This one change seems a little weird, but i'll give it some testing this weekend, now just o get the ddx/opengl bins installed/working. ;)

```
+-static char platformdevicename[] = "Vivante GCCore";
++static char platformdevicename[] = "Vivante GCCore:00";
```

**Comment by madduci** [comment]
Dear Robert

I took the modification as quoted here
http://jas-hacks.blogspot.it/2013/10/imx6-ubuntu-1304-debugging-gpu.html
At this link http://kowalczyk.ws/imx/linux-next.tar.xzyou could also
download a rootfs with Vivante, Galcore, vpu and MXS FB. enabled.
I've found ypu need also the firmware for vpu, available here
http://repository.timesys.com/buildsources/w/wandboard-firmware/wandboard-firmware-1.0/wandboard-firmware-1.0.tar.gz

Kind regards

Michele

On 8 January 2014 19:45, Robert Nelson notifications@github.com wrote:

> This one change seems a little weird, but i'll give it some testing this
> weekend, now just o get the ddx/opengl bins installed/working. ;)
> 
> +-static char platformdevicename[] = "Vivante GCCore";
> ++static char platformdevicename[] = "Vivante GCCore:00";
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RobertCNelson/armv7-multiplatform/issues/19#issuecomment-31864459
> .

## 

Michele Adduci
Computer Engineer

phone:  +49 176 74766888
web:     http://www.micheleadduci.net
mail:     info@micheleadduci.net

**Comment by ghost** [comment]
stupid question... but is blackibiza84's vivante patch implemented in branch v3.13.x or do I have to patch manually?

**Comment by RobertCNelson** [comment]
Double check patch.sh it's enabled

**Comment by ghost** [comment]
oh okay thank you... I was not sure if the 3 vivante patches do the same thing :)

**Comment by RobertCNelson** [comment]
I just pulled them from the freescale bsp, along with the author's changes in the 3rd patch, easier to keep in sync if freescale makes changes..

**Comment by muthukumarmk** [comment]
I tried the patches, it got compiled and able to load the modules.
Can you please suggest me how to test the Hardware acceleration in Wandboard with kernel 3.13.

If I play any video file with ffplay its not rendering smoothly.

Thanks for your support.

**Comment by madduci** [comment]
You need to enable xorg module for x11 acceleration, bit I don't have code
for it
Am 21.03.2014 10:08 schrieb "muthukumarmk" notifications@github.com:

**Comment by muthukumarmk** [comment]
Thanks..
Can you suggest me how I can test a video file.
