### ISSUE TITLE
New Vivante GC DRM Patch

### ISSUE THREAD

**Issue by madduci** [RobertCNelson/armv7-multiplatform#21]
Dear Robert
I've fixed the Vivante driver with latest updates. Now 3.14.4 kernel compiles without any error, if I enable Vivante module.
I didn't test it yet, but I'm sure it is going to work fine again.
As It was documented on Fedora's user forum, the drm_platform_exit is now deprecated, so I removed it.
I link you the git-patch:

http://pastebin.com/X5D6xJ7D

Best

Michele

**Comment by RobertCNelson** [comment]
Thanks Michele!
https://github.com/RobertCNelson/armv7-multiplatform/commit/12e8599f89cdfa06204d685849cd993cba5040b1
