### ISSUE TITLE
Linux-3.17.0-rc1-armv7-x0.3 on CM-510 board, does not boot.

### ISSUE THREAD

**Issue by gdobato** [RobertCNelson/armv7-multiplatform#24]
Hello,
I am trying to boot Linux 3.17 Kernel on CM-510 board, but it does not boot. The last output I am able to see is:

 Booting kernel from Legacy Image at 00200000 ...  
   Image Name:   Linux-3.17.0-rc1-armv7-x0.3  
   Created:      2015-01-18  11:58:43 UTC  
   Image Type:   ARM Linux Kernel Image (uncompressed)  
   Data Size:    3948368 Bytes =  3.8 MB  
   Load Address: 00008000  
   Entry Point:  00008000  
   Verifying Checksum ... OK  
   Loading Kernel Image ... OK  
OK                                                                                                                                                     

Starting kernel ...                                                                                                                                    

Uncompressing Linux... done, booting the kernel.            

I have made different checks in order to find out what's wrong:

1) I have tried different tty console specification on bootargs : ttyS0, ttyS1, ttyS2, ttyS0 ... just to make sure the problem is not related to the standard output specification during booting process.

2)In order to recieve further information about the issue, I have activated "earlyprintk" in menuconfig.
CONFIG_EARLY_PRINTK=y

3)Lastly, I have actived Kernel Low Level Debugging
CONFIG_DEBUG_LL=y

But, always the same...

I print my used bootargs:

CM-A510>> printenv
loads_echo=0
rootpath=/mnt/ARM_FS/
mtdids=nand0=dove-nand
mtdparts=mtdparts=dove-nand:4m(boot),-(rootfs)
arcNumber=3020
CASset=min
MALLOC_len=5
bootargs_root=root=/dev/nfs rw
bootargs_end=:::dove:eth0:none
image_name=kernel.img
tftpbootcmd=tftpboot 0x2000000 ${image_name}; setenv bootargs ${console} ${mtdparts} ${bootargs_root} nfsroot=${serverip}:${rootpath}  ip=${ipaddr}:${se 
standalone=fsload 0x2000000 ${image_name};setenv bootargs ${console} ${mtdparts} root=/dev/mtdblock0 rw ip=${ipaddr}:${serverip}${bootargs_end} usb0Mode;
bootnand=sflash read a0000 0x2000000 0x300000;setenv bootargs ${console} ${mtdparts} ubi.mtd=0 root=ubi0:rootfs rootfstype=ubifs rw usb0Mode=${usb0Mode};
disaMvPnp=no
usb0Mode=host
usb1Mode=host
lcd0_enable=0
lcd1_enable=1
lcd0_params=1280x768-24@60
lcd1_params=640x480-16@60
dnsip=192.168.10.13
loadaddr=0x200000
baudrate=115200
console=ttyS0,115200
ethprime=egiga0
ethaddr=00:01:c0:14:cd:d0
eth1addr=00:01:c0:14:cd:d9
serial#=CM-A510-C800-D1024-N512-E2-U4-I-A-V100-140302-0001c014cdd0-0001c014cdd9
ethact=egiga0
bootfile=bootscr.img
nemo_bootcmd=for j in 2 1 0; do 
echo stepj $j; 
mmc rescan $j;
for i in 0 1 2 3 4 5 6 7 8 9 a b c d e f 10 11 12 13 14 15 16 17 18 19; do 
mmc rescan $j; 
if fat load mmc $j:$i ${loadaddr} /uImage; then 
bootm ${loadaddr}; 
fi; 
if fat load mmc $j:$i ${loadaddr} /boot/uImage; then 
bootm ${loadaddr}; 
fi; 
if ext2load mmc $j:$i ${loadaddr} /uImage; then 
bootm ${loadaddr}; 
fi; 
if ext2load mmc $j:$i ${loadaddr} /boot/uImage; then 
bootm ${loadaddr}; 
fi; 
echo no device found in mmc $j partition $i; 
done; 
done
partition=nand0,0
mtddevnum=0
mtddevname=boot
filesize=2F0C44
fileaddr=200000
netmask=255.255.255.0
gatewayip=192.168.1.1
ipaddr=192.168.1.11
serverip=192.168.1.10
bootargs=root=/dev/nfs nfsroot=192.168.1.10:/home/devel/devel/cm-a510/a510 ip=dhcp console=ttyS0,115200 pm_disable useNandHal=4bitecc fbcon=rotate:1 usbe
stdin=serial
stdout=serial
stderr=serial
passDramInitTag=yes
mainlineLinux=yes
enaMonExt=no
pexMode=RC
disL2Cache=no
disL2Ecc=no
sata_dma_mode=yes
bootdelay=0
autoload=no
enaL2ExtraFeatures=yes
enaCpuStream=no
enaVpuPower=yes
enaGpuPower=yes

I would greatly appreciate your help in this matter

Thank you very much in advance.

GDobato

**Comment by RobertCNelson** [comment]
Don't you mean: "cm-a510" ?
http://www.compulab.co.il/products/computer-on-modules/cm-a510/

First, "Linux-3.17.0-rc1-armv7-x0.3" means you have a early branch, the current top of hte v3.17.x branch is "3.17.4-armv7-x3" so fix that first..

Second, this tree is device tree only, it looks like your just booting "uImage" so fix that..

Third, i don't have this device, and have disabled all Marvell devices by default.

Sorry, Good Luck! Not my bug.

Regards,

**Comment by gdobato** [comment]
Ok,

Thank you very much for your suggestions.

Best regards,

GDobato
