### ISSUE TITLE
wandboard quad c1 etnaviv

### ISSUE THREAD

**Issue by duperray** [RobertCNelson/armv7-multiplatform#31]
Hi,

etnaviv driver on 4.5 branch use to work very well on debian stretch, however I tested 4.6 and 4.7, the driver loads but a simple cursor is blinking on the upper left of the screen.

by the way, I had to append -armmp to version.sh because dpkg refused to install the build package if the flavor was wrong.

Thank you so much for providing theses easy to use build scripts.

Cheers

Pierre

**Comment by RobertCNelson** [comment]
hi @duperray

yeah i've fallen behind on my imx etnaviv testing. (v4.5.x was when i was testing it the most)

Double check that you are using:

https://github.com/austriancoder/libdrm

and the newest mesa branch:

https://github.com/etnaviv/mesa/tree/12.0_etnaviv

as i know debian stretch had a newer version of libdrm come down.

Regards,

**Comment by duperray** [comment]
Hi,

I was completely wrong,

the stretch debian kernel work perfectly well, I'm using console + xorg 
there (4.6.3) and your patched 4.7 branch kernel work
also very well.
Sorry for the noise... I don't know what happened!@#%

for the record, I have libdrm 2.4.68 on debian stretch.

for mesa, I did not test anything (11.2.2 available).
As soon as 12.0 will be packaged for stretch, I will try acceleration.
But wait a minute, there is no 3d games for arm? does it?

anyway, thank you very much to take time for you last reply.

Cheers,

Pierre
PS: you probably own many wandboard but if I can test on debian (as you 
seems to use ubuntu) for you or just help in anyway in "basic" testing
just ask :)

**Comment by duperray** [comment]
Hi,
the packaged kernel can't install on debian, because uboot need the dtbs to be in /usr/lib/linux-image-${uname -r}/
Another point is that dpkg refuse to install the package if you don't provide the correct flavor `-armmp'
in the package name (easy workaround is to put BUILD="-armmp" in version.sh).
thank you so much for your work

Cheers
Pierre

**Comment by RobertCNelson** [comment]
@duperray not sure what your complaining about, if you use debian's u-boot and flash-kernel packages you will have issues with my repo..

Either use the "netinstall" i provide

https://github.com/RobertCNelson/netinstall

or the step by step directions here:

https://eewiki.net/display/linuxonarm/Wandboard

Or you can just wait till Stretch+1 when debian integrates all of this. ;)

Regards,

**Comment by duperray** [comment]
Hey robert, I'm not complaining ;)
Thanks for the links, I did not realize I had to use a customized netinstall for your armv7-multiplatform repo.
I only installed with the jessie installer thru the serial link and later upgraded to stretch.
I tested a few of your kernels the 4.5 was a good one for me because it provided video.
unfortunately, after switching to the stock debian 4.8 kernel, video broke again.
So I tested (I have a wandboard quad rev1c) your 4.8.x, same pb, tryied the 4.9.x, same pb, now
using your 4.10.x and TADA, video again :)
the only thing is, I have to dpkg -x the builded .deb linux image and manually copy the dtbs in /usr/lib
see https://packages.debian.org/stretch/armhf/linux-image-4.8.0-2-armmp/filelist
(the official stretch 4.8 kernel put *.dtb in /usr/lib/linux-image-`uname -r')
or uboot during installation of the kernel complain about this (uboot, not me ;)
How heavily did you change the netinstall? it's completely different project from the debian netinstall?
Regards,

Pierre

**Comment by RobertCNelson** [comment]
So the netinstall is just a wrapper around debian's debian-installer..

- It provides its own u-boot
- provides a mainline kernel (with patches for enablement of devices not support by debian yet)
- preseed file with a generic default partition layout
- adds repos.rcn-ee.net
- neuter's flash-kernel

flash-kernel: this is the pain, unless your board is supported by debian, flash-kernel goes out of it's way to do things "it" want's to do.. So we override the flash-kernel database, this let's us "just" install the linux-image*.deb, and allow a grub inspired script setup the vmlinuz/dtbs in the correct location in the boot directory.

flash-kernel: it's what is forcing "armmp"..

flash-kernel: https://sources.debian.net/src/flash-kernel/3.73/db/all.db/#L1381
```
Machine: Wandboard i.MX6 Quad Board
Kernel-Flavors: armmp
DTB-Id: imx6q-wandboard.dtb
Boot-Script-Path: /boot/boot.scr
U-Boot-Script-Name: bootscr.wandboard
Required-Packages: u-boot-tools
```

Now look what we patch in:
https://github.com/RobertCNelson/netinstall/blob/master/lib/flash_kernel/all.db#L2460
```
Machine: Wandboard i.MX6 Quad Board
Method: generic
```
and here's our linux-image post install:

https://github.com/RobertCNelson/netinstall/blob/master/lib/shared/zz-uenv_txt

in the most generic case, it just updates uname_r in /boot/uEnv.txt, so U-Boot knows what vmlinuz/dtb to load..

Regards,

**Comment by duperray** [comment]
Robert,
Thx for the explanation, I have a long way to go but I think I will follow your advice and wipe out my mmc and give a go to your netinstall. Hopefully after some learning I could do more useful comments and testing on the wandboard.
Thanks again for your time.
