### ISSUE TITLE
there is nothing after staring kernel...

### ISSUE THREAD

**Issue by j824737450** [RobertCNelson/armv7-multiplatform#42]
When I boot  the kernel ,there is nothing after staring kernel...
![1](https://user-images.githubusercontent.com/33032927/34319897-44f73bd4-e828-11e7-8663-38d41e844f44.png)

**Comment by aureq** [comment]
@j824737450 If you want some help on your problem, you should definitely provide more information such as platform, kernel configuration, kernel version, toolchain version and so on. Also, while some people might be able to help you, I would recommend the following :
* try contacting a user forum dedicated to your board. That's where you will find a lot of knowledge and help
* try using a known working kernel (ie: something you didn't compile) so you can rule out uBoot configuration from the equation

**Comment by RobertCNelson** [comment]
@j824737450 smeels like i.MX6x SABRE Lite, sadly mine are no longer used, probally last tested v4.9.x on them.  Replaced with a few wandboards with double the memory..
