### ISSUE TITLE
UDOO missing ttymxc3

### ISSUE THREAD

**Issue by mkuf** [RobertCNelson/armv7-multiplatform#44]
Hi There, 

in 9d78e965814ae061e2cc9efd3eb276c236109442 there was a patch added to sync the pincfgs with UDOOboard/linux_kernel which is missing since 4.8.x
Therefore uart4 (/dev/ttymxc3) which is used to communicate with the onboard sam3x is not available. 

Manually applying the old Patch creates an error while compiling, a stripped down version to add only the pincfg for uart4 works fine (tested with 4.9.x).

```
diff --git a/arch/arm/boot/dts/imx6qdl-udoo.dtsi b/arch/arm/boot/dts/imx6qdl-udoo.dtsi
index a173de2..31eceea 100644
--- a/arch/arm/boot/dts/imx6qdl-udoo.dtsi
+++ b/arch/arm/boot/dts/imx6qdl-udoo.dtsi
@@ -177,6 +177,13 @@
                        >;
                };

+               pinctrl_uart4: uart4grp {
+                       fsl,pins = <
+                               MX6QDL_PAD_KEY_COL0__UART4_TX_DATA      0x1b0b1
+                               MX6QDL_PAD_KEY_ROW0__UART4_RX_DATA      0x1b0b1
+                       >;
+               };
+
                pinctrl_usbh: usbhgrp {
                        fsl,pins = <
                                MX6QDL_PAD_GPIO_17__GPIO7_IO12  0x1b0b0
@@ -247,6 +254,12 @@
        status = "okay";
 };

+&uart4 { // iMX6-Arduino internal serial port - ttymxc3
+       pinctrl-names = "default";
+       pinctrl-0 = <&pinctrl_uart4>;
+       status = "okay";
+};
+
 &usbh1 {
        pinctrl-names = "default";
        pinctrl-0 = <&pinctrl_usbh>;

```

**Comment by RobertCNelson** [comment]
@voodoo-bravo i'd post this asap to the mailing list, things are closing up quickly for v4.20/v5 this week, so this could get in the next release..  (i don't see a reason why this shouldn't be mainline)

otherwise i'll add this to my main dev branch..

Regards,

**Comment by mkuf** [comment]
@RobertCNelson Good point. I'll dig through the contribution guide and let you know if the patch gets accepted. 
Thanks!

**Comment by RobertCNelson** [comment]
For imx soc's, my git send-email notes are:

```bash
--to "shawn.guo@linaro.org"
--cc "devicetree@vger.kernel.org"
--cc "linux-arm-kernel@lists.infradead.org"
```

**Comment by mkuf** [comment]
FYI: https://www.spinics.net/lists/devicetree/msg252064.html

**Comment by mkuf** [comment]
The patch was merged into linux-next, so I'm closing this issue. 

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/arch/arm/boot/dts/imx6qdl-udoo.dtsi?h=next-20181106 

Thanks for your Help.

**Comment by sarnold** [comment]
The patches for udoo uart and arduino driver are linked here if you need them; should work on newer kernels, I just haven't had time to test them lately...

https://wiki.gentoo.org/wiki/Udoo
https://github.com/gentoo/arm/tree/master/sys-kernel/armv7multi-sources/files
