### ISSUE TITLE
Build stops without error output

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#5]
When building with build_kernel.sh compilation stops without any error message:

  CC [M]  fs/xfs/xfs_rtalloc.o
  CC [M]  fs/xfs/xfs_acl.o
  CC [M]  fs/xfs/xfs_stats.o
  CC [M]  fs/xfs/xfs_sysctl.o
  LD [M]  fs/xfs/xfs.o
  LD      fs/built-in.o
[user@server armv7-multiplatform]$

When I issue make in directory KERNEL I get an error message

[user@server KERNEL]$ make
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  CHK     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  BC      kernel/timeconst.h
/bin/sh: bc: command not found
make[1]: **\* [kernel/timeconst.h] Error 127
make: **\* [kernel] Error 2
[user@server KERNEL]$

Why does your script show no error message?

**Comment by RobertCNelson** [comment]
It would show the error if we built with:

"make -j1" but instead it gets buried under "make -jnumber_of_cores"... (first error occurs and stops the build, but it takes awhile for the other threads to wind down..)

Too keep the error from occurring, we do a pkg install check on debian based distros...
https://github.com/RobertCNelson/stable-kernel/blob/master/tools/host_det.sh

Anything else is really left up to the end user to fix/patch/etc..

Regards,

**Comment by bentwire** [comment]
Would you like package check for Fedora?  I use Fedora, so far your scripts
have worked beautifully so I have not run in to any issues, but I could add
a Fedora package check if you wish and send a push request.

Mike

**Comment by RobertCNelson** [comment]
Fedora/CentOS should now be taken care of, just ping me if i'm late on a future Fedora release...
