### ISSUE TITLE
Wrong package names in build_deb.sh

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#6]
build_deb.sh creates the following files in deploy

3.11.0-rc3-armv7-x5-dtbs.tar.gz        linux-headers-3.11.0-rc3-armv7-x5_1.0cross_armhf.deb  test
3.11.0-rc3-armv7-x5-firmware.tar.gz    linux-image-3.11.0-rc3-armv7-x5_1.0cross_armhf.deb
linux-firmware-image_1.0cross_all.deb  linux-libc-dev_1.0cross_armhf.deb

linux-firmware-image_1.0cross_all.deb contains files in directory ./lib/firmware/3.11.0-rc3-armv7-x5/.
So why is the image called 1.0 and not  3.11.0-rc3-armv7-x5

**Comment by RobertCNelson** [comment]
That's just the way the mainline builddeb script (make deb-pkg) outputs those files:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/scripts/package/builddeb#n81
packagename=linux-image-$version
fwpackagename=linux-firmware-image
kernel_headers_packagename=linux-headers-$version
libc_headers_packagename=linux-libc-dev

firmware/libc does not get the $version tag..

Regards,

**Comment by xypron** [comment]
A patch to correct builddeb has been accepted by the kernel maintainer.

https://git.kernel.org/cgit/linux/kernel/git/mmarek/kbuild.git/commit/?h=misc&id=95e2a7d80779850341b45b4fbc2a0041bfc378fb
