### ISSUE TITLE
CONFIG_FANOTIFY_ACCESS_PERMISSIONS

### ISSUE THREAD

**Issue by xypron** [RobertCNelson/armv7-multiplatform#7]
Hello Robert,

in Ubuntu and Fedora CONFIG_FANOTIFY_ACCESS_PERMISSIONS is enabled by default.

Could you, please, apply the following patch to the 3.11 branch.

Best regards

Signed-off-by: Heinrich Schuchardt xypron.glpk@gmx.de

---

 patches/defconfig |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/patches/defconfig b/patches/defconfig
index fd6ecb3..c8aade8 100644
--- a/patches/defconfig
+++ b/patches/defconfig
@@ -4516,7 +4516,7 @@ CONFIG_FSNOTIFY=y
 CONFIG_DNOTIFY=y
 CONFIG_INOTIFY_USER=y
 CONFIG_FANOTIFY=y
-# CONFIG_FANOTIFY_ACCESS_PERMISSIONS is not set
+CONFIG_FANOTIFY_ACCESS_PERMISSIONS=y
 CONFIG_QUOTA=y
 CONFIG_QUOTA_NETLINK_INTERFACE=y
 # CONFIG_PRINT_QUOTA_WARNING is not set

**Comment by RobertCNelson** [comment]
Thanks Heinrich,

Pushed: https://github.com/RobertCNelson/armv7-multiplatform/commit/49bd8edd50be4e7e75e5969f4c718f1fdef5dbea
